CREATE DATABASE Liga;

USE Liga;

CREATE TABLE Korisnik
(
ID INT IDENTITY(1,1) PRIMARY KEY,
Imejl NVARCHAR(20),
Lozinka NVARCHAR(20),
Uloga INT
)

CREATE TABLE Sezona
(
ID INT IDENTITY(1,1) PRIMARY KEY,
Naziv NVARCHAR(7)--izgleda ovako: 2021-22
)

CREATE TABLE Klub
(
ID INT IDENTITY(1,1) PRIMARY KEY,
Naziv NVARCHAR(20)
)
/*
DROP TABLE Sezona;
DROP TABLE Korisnik;
DROP TABLE Klub;
DROP TABLE Igrac;
*/
CREATE TABLE Igrac
(
ID INT IDENTITY(1,1) PRIMARY KEY,
Ime NVARCHAR(20),
Prezime NVARCHAR(20),
KlubID INT,
FOREIGN KEY(KlubID) REFERENCES Klub(ID)
)

CREATE TABLE Mec
(
ID INT IDENTITY(1,1) PRIMARY KEY,
Klub1ID INT,
Klub2ID INT,
Datum DATE,
SezonaID INT,
FOREIGN KEY(Klub1ID) REFERENCES Klub(ID),
FOREIGN KEY(Klub2ID) REFERENCES Klub(ID),
FOREIGN KEY(SezonaID) REFERENCES Sezona(ID)
)

CREATE TABLE Gol
(
ID INT IDENTITY(1,1) PRIMARY KEY,
StrelacID INT,
AsistiraoID INT,
MecID INT,
FOREIGN KEY(StrelacID) REFERENCES Igrac(ID),
FOREIGN KEY(AsistiraoID) REFERENCES Igrac(ID),
FOREIGN KEY(MecID) REFERENCES Mec(ID)
)

CREATE TABLE ZutiKarton
(
ID INT IDENTITY(1,1) PRIMARY KEY,
IgracID INT,
MecID INT,
FOREIGN KEY(IgracID) REFERENCES Igrac(ID),
FOREIGN KEY(MecID) REFERENCES Mec(ID)
)

CREATE TABLE CrveniKarton
(
ID INT IDENTITY(1,1) PRIMARY KEY,
IgracID INT,
MecID INT,
FOREIGN KEY(IgracID) REFERENCES Igrac(ID),
FOREIGN KEY(MecID) REFERENCES Mec(ID)
)

CREATE VIEW MecPogled
AS
SELECT Mec.ID, Prvi.Naziv AS Klub1,
(SELECT COUNT(*) FROM Gol JOIN Igrac ON Gol.StrelacID = Igrac.ID WHERE MecID = Mec.ID AND Igrac.KlubID = Prvi.ID) AS Golovi1, 
(SELECT COUNT(*) FROM Gol JOIN Igrac ON Gol.StrelacID = Igrac.ID WHERE MecID = Mec.ID AND Igrac.KlubID = Drugi.ID) AS Golovi2, 
Drugi.Naziv AS Klub2, Mec.Datum, Sezona.Naziv
FROM Mec JOIN Klub Prvi ON Mec.Klub1ID = Prvi.ID 
JOIN Klub Drugi ON Mec.Klub2ID = Drugi.ID 
JOIN Sezona ON Mec.SezonaID = Sezona.ID;

SELECT * FROM MecPogled;
DROP VIEW MecPogled;